spring:
  datasource:
    url: jdbc:postgresql://localhost:9999/test_snt_database?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
    show-sql: true
#  sql:
#    init:
#      schema-locations: classpath:sqlScript/data-init-dev.sql


logging:
  level:
    root: INFO
    org.springframework.security: INFO
    test: debug
    SQL: debug
